In [9]:
##############
#K. David Roell CFPB 7/12/16
#expands data selection for quality edits to include context for developing statistical approaches
#will attemtp to segment mortgage market participants by loan activity by:
#volume/count of lending, income of applicants, securitization, property type and other factors
##############

import json
import os
import pandas as pd
import psycopg2
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
get_ipython().magic(u'matplotlib inline')
matplotlib.style.use('ggplot')
#from macro_sql import Q076 
with open('quality_sql.json') as f: #FIXME change to quality_sql.json and refactor the rest of code
    edit_sql = json.load(f)
    
#parameter format for local use #consider changing hmdamaster to roellk if db changes cause a fail
params = {
'dbname':'hmdamaster',
'user':'roellk',
'password':'',
'host':'localhost',
}

try:
    conn = psycopg2.connect(**params)
    cur = conn.cursor()
    print("i'm connected")

except psycopg2.Error as e: #if database connection results in an error print the following
    print("I am unable to connect to the database: ", e)

i'm connected

In [1]:
#get distributions of values for fields
def field_dist(field='income', table='hmdalar2014', prop_type='1', loan_purp='1', loan_type='1'):
    dist_sql = """SELECT DISTINCT year, {field}, COUNT({field}) FROM {table} """.format(table=table, field=field) 
    #removing the bulk of quesitonable data in exploration by removing HUD
    where_sql = """WHERE agency != '7' AND property_type IN ('{prop_type}') AND loan_purpose IN ('{loan_purp}') 
    AND loan_type IN ('{loan_type}') """.format(prop_type=prop_type, loan_purp=loan_purp, loan_type=loan_type)
    order_sql = """ORDER by {field} ASC """.format(field=field)
    group_sql = """GROUP BY {field}, year """.format(field=field)
    return dist_sql + where_sql + group_sql + order_sql

In [ ]:
#get distributions of values for fields
def field_dist_geo(field='income', table='hmdalar2014', prop_type='1', loan_purp='1', loan_type='1'):
    dist_sql = """SELECT DISTINCT year, CONCAT(state,county,tract) {field}, COUNT({field}) FROM {table} """.format(table=table, field=field) 
    #removing the bulk of quesitonable data in exploration by removing HUD
    where_sql = """WHERE agency != '7' AND property_type IN ('{prop_type}') AND loan_purpose IN ('{loan_purp}') 
    AND loan_type IN ('{loan_type}') """.format(prop_type=prop_type, loan_purp=loan_purp, loan_type=loan_type)
    order_sql = """ORDER by {field} ASC """.format(field=field)
    group_sql = """GROUP BY year, CONCAT(state,county,tract), {field}""".format(field=field)
    return dist_sql + where_sql + group_sql + order_sql

In [11]:
year = 2014
first = True
field = 'income'
while year > 2003:
    table = 'hmdalar' + str(year)
    print(table)
    cur.execute(field_dist(table=table, field=field))        
    data_df = pd.DataFrame(cur.fetchall())

    col_names = [desc[0] for desc in cur.description]
    if len(data_df.columns) == len(col_names):
        print('setting column names')
        data_df.columns = col_names

    if first == True and len(data_df.columns) > 0:
        dist_df = data_df.copy()
        first = False

    elif first == False and len(data_df.columns) > 0:
        print('merging dataframes')
        dist_df=dist_df.merge(data_df, how='outer')

    else:
        print('no data returned from query')

    print(dist_df.head())
    path = 'dist_csvs/'
    if not os.path.exists(path):
        os.makedirs(path)
    
    year -= 1
dist_df.to_csv(path + '{field}_dist.csv'.format(field=field),index=False)

hmdalar2014
setting column names
   year income  count
0  2014   0001    574
1  2014   0002    217
2  2014   0003    202
3  2014   0004    231
4  2014   0005    259
hmdalar2013
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2012
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2011
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2010
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2009
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2008
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2007
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2006
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2005
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0
hmdalar2004
setting column names
merging dataframes
   year income  count
0  2014   0001  574.0
1  2014   0002  217.0
2  2014   0003  202.0
3  2014   0004  231.0
4  2014   0005  259.0